export const REQUEST_POSTS = 'REQUEST_POSTS';
export const REQUEST_POSTS_SUCCESS = 'REQUEST_POSTS_SUCCESS';
export const REQUEST_POSTS_ERROR = 'REQUEST_POSTS_ERROR';
export const VOTE = 'VOTE';
export const SUBMIT_POST = 'SUBMIT_POST';
export const TITLE_CHANGE = 'TITLE_CHANGE';
export const SUMMARY_CHANGE = 'SUMMARY_CHANGE';